version: '3.2'
services:
  mysql:
    image: mysql:latest
    # volumes:
    # ./db:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: username
      MYSQL_PASSWORD: password
  wordpress:
    build: ./dockerfile/
    ports:
      - 8080:80
    # volumes:
    #   - ./wp:/var/www/html
    depends_on:
      - mysql
