version: '3.2'
services:
  mysql:
    image: mysql:5.7
    # volumes:
    # ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: wordpress
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pw
  wordpress:
    build: ./dockerfile/
    ports:
      - 8080:80
    # volumes:
    #   - ./wp:/var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: mysql_user
      WORDPRESS_DB_PASSWORD: mysql_pw

